<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-Q44GKQB" ignored="2" name="herokuapp-page-factory-sunil" tests="1" failures="1" timestamp="2022-12-11T20:30:44 AEST" time="10.166" errors="0">
  <testcase name="userShouldLoginSuccessfullyWithValidCredentials" time="0.247" classname="com.herokuapp.internet.the.testsuite.LoginPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.herokuapp.internet.the.pages.LoginPage.enterUserName(LoginPage.java:36)
at com.herokuapp.internet.the.testsuite.LoginPageTest.userShouldLoginSuccessfullyWithValidCredentials(LoginPageTest.java:21)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- userShouldLoginSuccessfullyWithValidCredentials -->
  <testcase name="verifyThePasswordErrorMessage" time="0.0" classname="com.herokuapp.internet.the.testsuite.LoginPageTest">
    <ignored/>
  </testcase> <!-- verifyThePasswordErrorMessage -->
  <testcase name="verifyTheUsernameErrorMessage" time="0.0" classname="com.herokuapp.internet.the.testsuite.LoginPageTest">
    <ignored/>
  </testcase> <!-- verifyTheUsernameErrorMessage -->
</testsuite> <!-- herokuapp-page-factory-sunil -->
